# Generated by Django 3.0.6 on 2020-05-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_desc',
        ),
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(default=0, max_length=10, verbose_name='возрастной рейтинг'),
        ),
        migrations.AddField(
            model_name='product',
            name='developer',
            field=models.CharField(blank=True, max_length=100, verbose_name='разработчик'),
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(blank=True, max_length=50, verbose_name='жанр'),
        ),
        migrations.AddField(
            model_name='product',
            name='image01',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image02',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image03',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image04',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image05',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image06',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(default='Русский', max_length=30, verbose_name='язык'),
        ),
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(default='PS4', max_length=20, verbose_name='платформа'),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, verbose_name='издатель'),
        ),
        migrations.AddField(
            model_name='product',
            name='released',
            field=models.CharField(blank=True, max_length=10, verbose_name='дата выхода'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.TextField(blank=True, verbose_name='ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
    ]
