# Generated by Django 3.0.6 on 2020-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200521_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='map',
            field=models.CharField(blank=True, max_length=200, verbose_name='карта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(default='Краснодар', max_length=128, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.CharField(default='18+', max_length=10, verbose_name='возрастной рейтинг'),
        ),
    ]
