# Generated by Django 3.0.6 on 2020-05-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200521_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='map',
        ),
    ]
