# Generated by Django 2.2.13 on 2020-06-08 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0004_debug_admin_recreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 20, 19, 22, 18523, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
