# Generated by Django 2.2.13 on 2020-06-11 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0008_auto_20200611_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 10, 25, 7, 941947, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
