# Generated by Django 2.2.13 on 2020-06-12 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0009_auto_20200611_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 14, 11, 8, 17, 68929, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
