# Generated by Django 2.2.13 on 2020-06-28 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0010_auto_20200612_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 19, 22, 31, 212880, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
